version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: api-php
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        environment:
            APP_NAME: ${APP_NAME}
            APP_ENV: ${APP_ENV}
            DB_CONNECTION: ${DB_CONNECTION}
            DB_HOST: db
            DB_PORT: ${DB_PORT}
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
        networks:
            - laravel

    db:
        image: mysql:8.0
        container_name: api-db
        ports:
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
        restart: always
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel

volumes:
    dbdata:

networks:
    laravel:
